language: node_js
node_js:
  - "12"
  - "10"
  - "8"
env:
  - MONGOOSE_VERSION=5
  - MONGOOSE_VERSION=4
services: mongodb
cache: yarn
git:
  depth: 3
before_script:
  - sleep 15
install:
  - yarn
  - yarn add --dev mongoose@^$MONGOOSE_VERSION
script:
  - yarn test:all
jobs:
  include:
  - stage: deploy
    if: env(MONGOOSE_VERSION) = 5
    node_js: "12"
    script:
      - yarn test:coverage
      - yarn coveralls
